import { Avatar, IconButton, Paper } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Sidebar from '../components/Sidebar/Sidebar';
import * as Style from '../styles';
import MoreVertIcon from '@mui/icons-material/More';
import { useContext } from 'react';
import { SidebarContext } from '../context';

const Home: NextPage = () => {
  const { showSidebar, setShowSidebar } = useContext(SidebarContext);

  return (
    <div>
      <Head>
        <title>Whats App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ display: 'flex' }}>
        <Sidebar />
        <Style.Container>
          <Style.Header>
            <Avatar src={'U'} />

            <Style.HeaderInformation>
              <h3>Unknown</h3>
              <p>Last active : Unknown</p>
            </Style.HeaderInformation>
            <Style.HeaderIcon>
              <IconButton onClick={() => setShowSidebar(!showSidebar)}>
                <MoreVertIcon />
              </IconButton>
            </Style.HeaderIcon>
          </Style.Header>
        </Style.Container>
      </main>
    </div>
  );
};

export default Home;
